server:
  port: 8008
  forward-headers-strategy: NATIVE	
  servlet:
    context-path: /insursa-usage-metric		

spring:
  application:
    name: insursa-usage-metric
  datasource:
    url: jdbc:mysql://localhost:3306/insursa_premium
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1/oauth2/jwks		